! Copyright (C) 2024 by E. Lamprecht
! See LICENSE.md in this repository.

MODULE CONSTANT
  IMPLICIT NONE

  INTEGER,PARAMETER :: RKIND=8          ! DOUBLE PRECISION
  INTEGER,PARAMETER :: IFU=21           ! UNIT FOR TEMPORARY FILES (INPUT)
  INTEGER,PARAMETER :: OFU=22           ! UNIT FOR TEMPORARY FILES (OUTPUT)
  
END MODULE CONSTANT
