! Copyright (C) 2024 by E. Lamprecht
! See LICENSE.md in this repository.

#ifndef DIFN
#define DIFN 'input.ppm'
#endif

#ifndef DWFN
#define DWFN '/usr/lib/mz2wave.tbl'
#endif

#ifndef DOFN
#define DOFN 'output.au'
#endif

#ifndef DCHS
#define DCHS 'RGBM'
#endif

#ifndef DVMUL
#define DVMUL 1.0_RKIND
#endif

#ifndef DACPS
#define DACPS 10
#endif

#ifndef DSMPR
#define DSMPR 44100
#endif

#ifndef DNCHAN
#define DNCHAN 2
#endif

#ifndef DNTPC
#define DNTPC 2**16
#endif
