FC=gfortran
CFLAGS=-cpp -Wall -O3 -Ofast -fopenmp -ffast-math -flto
EXE=mz2
OBJ=constant.o caseconv.o logist.o wvecmp.o pflags.o sfrealcomp.o \
    fimagemod.o mzosc.o mzpnl.o mzaufile.o mzsynth.o

$(EXE) : $(OBJ)
	$(FC) $(CFLAGS) -o $(EXE) $(OBJ)

%.o : %.f
	$(FC) $(CFLAGS) -std=f2008 -c $<

%.o : %.f95
	$(FC) $(CFLAGS) -std=f2008 -c $<

all : $(EXE)

clean :
	rm *.o *.mod

veryclean :
	rm *.o *.mod $(EXE)
