name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Show working directory and contents
      run: |
             pwd ; 
             ls ;

    - name: Change directory and build project
      run: |
             cd SOURCE ; 
             make -f Makefile.gfortran all clean ;
             move mz2.exe ..\WINEXE ;                         
