name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Change directory
      run: cd ./SOURCES
    - name: Make all
      run: make -f Makefile.gfortran all clean
