name: Windows Makefile CI

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Change directory, build project and run with -help
      run: |             
             cd SOURCE ;
             gcc --version ;
             make -f Makefile.gfortran all clean ;
             rm ..\WINEXE\*.exe
             mv mz2.exe ..\WINEXE ;
             dir ..\WINEXE ;
             echo '' ;
             ..\WINEXE\mz2 -help ;

    - name: Commit changes
      run: |
            git config user.name github-actions ;
            git config user.email github-actions@github.com ;
            git add --all
            git commit -m "Yay, windows executable generated" ;
            git push ;
