name: Windows Makefile CI

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Change directory, build project and run with -help
      run: |             
             cd SOURCE ;
             gcc --version ;
             make -f Makefile.gfortran all clean ;
             rm ..\BIN\WIN64\*.*
             mv mz2.exe ..\BIN\WIN64 ;
             dir ..\BIN\WIN64 ;
             echo '' ;
             ..\BIN\WIN64\mz2 -help ;

    - name: Commit changes
      run: |
            git config user.name github-actions ;
            git config user.email github-actions@github.com ;
            git add --all
            git commit -a -m "Yay, Windows executable generated" ;
            git push ;
